name: my-workflow-name

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ls
      run: ls
    - name: build
      run: cmake -H. -B_build -DBUILD_TESTS=ON
    - name: test
      run: cmake --build _build --target test
